name: Auto Update Events Page

on:
  push:
    branches: [main]
  schedule:
    - cron: '0 0 * * 0'  # Runs every Sunday at midnight UTC
  workflow_dispatch:  # Allows manual triggering

jobs:
  update-events:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install Jinja2

      - name: Run script to generate new events page
        run: python generate_html.py

      - name: Configure Git user
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Commit and push changes
        env:
          TOKEN: ${{ secrets.PAT_TOKEN }}
        run: |
          # Use token to authenticate and push changes
          git add index.html
          git commit -m "Auto-update index page" || echo "No changes to commit"
          
          # Explicitly authenticate using PAT_TOKEN
          git push https://$TOKEN@github.com/mylesgrxnt/snowflake-page.git main
